name: Run Tests 

on: 
  push: 
    branches: [ master ] # На ветку main
  pull_request: # При создании Pull Request
    branches: [ master ]

jobs: 
  build-and-test: 
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Указывает на использование последней патч-версии .NET 6

    - name: Install dependencies 
      run: dotnet restore 

    - name: Build 
      run: dotnet build --no-restore 

    - name: Test 
      run: dotnet test --no-build --verbosity normal 


