name: Run Tests 

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  checks: write
  pull-requests: write
  
jobs: 
  build-and-test: 
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Указывает на использование последней патч-версии .NET 6

    - name: Install dependencies 
      run: dotnet restore 
      
    - name: Install jq
      run: sudo apt-get install jq
      
    - name: Update appsettings.json
      run: |
        jq '.Header = "true"' appsettings.json > temp.json && mv temp.json appsettings.json
        
    - name: Build 
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --logger:"nunit;LogFilePath=test-results.xml"

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: '**/test-results.xml'
